# Generated by Django 4.2.7 on 2023-11-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Removebaground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uplodedimage', models.ImageField(upload_to='media/')),
                ('remove_bg', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
