# Generated by Django 4.2.7 on 2023-11-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='removebaground',
            name='remove_bg',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='removebaground',
            name='uplodedimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
